spring:
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: info

naver-open-api:
  short-url:
    url: https://openapi.naver.com/v1/util/shorturl
    client-id: ogmMBNSWeVTHyrq7DayR
    secret: U5oExG5aTe